<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130305160003 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // Initialize the eZ Script Interface.
        $this->script = $this->getEzScriptInstance( null );

        $adminRole = \eZRole::create('MyVideo Administration');
        $adminRole->appendPolicy('*', '*');
        $adminRole->store();

        $limitationsList = array(
            'Class' => array(
                'article',
                'folder',
                'frontpage',
                'myvideo_menu_flyout',
                'myvideo_menu',
                'myvideo_menu_item',
                'myvideo_solr_query',
                'myvideo_sushibar',
                'myvideo_video',
                'myvideo_videolist',
                'myvideo_homepage'
            )
        );

        $contentRole = \eZRole::create('MyVideo Inhalte bearbeiten');
        $contentRole->appendPolicy('content', 'create', $limitationsList);

        $contentRole->appendPolicy('content', 'edit', $limitationsList);
        $contentRole->appendPolicy('content', 'read', $limitationsList);
        $contentRole->appendPolicy('content', 'remove', $limitationsList);
        $contentRole->appendPolicy('content', 'versionview', $limitationsList);
        $contentRole->appendPolicy('content', 'bookmark', $limitationsList);
        $contentRole->appendPolicy('ezoe', '*');
        $contentRole->store();

        $loginRole = \eZRole::create('MyVideo Anmeldung am Backend');
        $loginRole->appendPolicy('content', 'dashboard');
        $loginRole->appendPolicy('user', 'login');
        $loginRole->store();

        $this->script->shutdown();
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $role = \eZRole::fetchByName('MyVideo Administration');
        $role->remove();

        $role = \eZRole::fetchByName('MyVideo Inhalte bearbeiten');
        $role->remove();

        $role = \eZRole::fetchByName('MyVideo Anmeldung am Backend');
        $role->remove();

    }
}
