<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130603190519 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->installPackage('myvideo_image_teaser', 'myvideo_image_teaser-2.3-1.ezpkg');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo Video - add an image attribute DVD Cover.';" )
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_image_teaser');
    }
}
