<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130607152326 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("CREATE TABLE IF NOT EXISTS myvideotracking (
            contentobject_id integer default NULL,
            ivw_agofcode varchar(40),
            ivw_path varchar(255),
            ga_tvbrand varchar(255),
            ga_channel varchar(255),
            PRIMARY KEY (contentobject_id)
          );
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql("DROP TABLE IF EXISTS myvideotracking");
    }
}
