<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130419163226 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->installPackage('myvideo_video', 'myvideo_video-1.3-1.ezpkg');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo Video - add the Date/Time Picker attributes to publishing or expriation';" )
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_video');
    }
}
