<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130618170735 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        $this->installPackage('myvideo_tagpage', 'myvideo_tagpage-1.3-1.ezpkg');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo TagPage Updates and extend Redis export';" )
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_tagpage');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo TagPage Updates and extend Redis export';" )
        );
    }
}
