<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130424154217 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
    	$this->installPackage('myvideo_tagpage', 'myvideo_tagpage-1.2-1.ezpkg');
    	$this->addSql(
    			sprintf( "SELECT 'Success: MyVideo Tagpage - added missing fields videolist, wikipediaTag';" )
    	);
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
    	$this->removePackage('myvideo_tagpage');
    }
}
