<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130606131528 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        $this->installPackage('myvideo_video', 'myvideo_video-2.2-1.ezpkg');
        $this->installPackage('myvideo_image_teaser', 'myvideo_image_teaser-2.6-1.ezpkg');
        $this->installPackage('myvideo_sushibar', 'myvideo_sushibar-1.2-1.ezpkg');
        $this->addSql(
            sprintf("SELECT 'Success: MyVideo Video/Image Teaser/Sushibar - Added more icons.';")
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_video');
        $this->removePackage('myvideo_image_teaser');
        $this->removePackage('myvideo_sushibar');

    }
}
