<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130611165707 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        $this->installPackage('myvideo_video', 'myvideo_video-2.4-1.ezpkg');
        $this->installPackage('myvideo_image_teaser', 'myvideo_image_teaser-2.8-1.ezpkg');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo Video/Image Teaser - DVD Cover added...again.';" )
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_video');
        $this->removePackage('myvideo_image_teaser');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo Video/Image Teaser DVD Cover flag removed...again;'" )
        );
    }
}
