<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130725111622 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        // installing package
        $this->installPackage('myvideo_tagpage', 'myvideo_tagpage-1.4-1.ezpkg');
        $this->addSql(
            sprintf( "SELECT 'Success: MyVideo Tagpage - added social widget';" )
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->removePackage('myvideo_tagpage');
    }
}
