<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131216095858 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE ezcobj_state_group_language SET real_language_id = language_id & ~1;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
