<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130510124237 extends eZPublishPackageMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("CREATE TABLE IF NOT EXISTS xrowworkflow (
        contentobject_id integer default NULL,
        publish integer NOT NULL default '0',
        expire integer NOT NULL default '0',
        PRIMARY KEY  (contentobject_id)
        );");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql("DROP TABLE IF EXISTS xrowworkflow");
    }
}
